/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libgetar_wrap;

public final class Behavior {
  public final static Behavior Constant = new Behavior("Constant");
  public final static Behavior Discrete = new Behavior("Discrete");
  public final static Behavior Continuous = new Behavior("Continuous");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Behavior swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Behavior.class + " with value " + swigValue);
  }

  private Behavior(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Behavior(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Behavior(String swigName, Behavior swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Behavior[] swigValues = { Constant, Discrete, Continuous };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

