/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libgetar_wrap;

public final class CompressMode {
  public final static CompressMode NoCompress = new CompressMode("NoCompress");
  public final static CompressMode FastCompress = new CompressMode("FastCompress");
  public final static CompressMode MediumCompress = new CompressMode("MediumCompress");
  public final static CompressMode SlowCompress = new CompressMode("SlowCompress");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CompressMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CompressMode.class + " with value " + swigValue);
  }

  private CompressMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CompressMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CompressMode(String swigName, CompressMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CompressMode[] swigValues = { NoCompress, FastCompress, MediumCompress, SlowCompress };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

