/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libgetar_wrap;

public class GTAR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GTAR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libgetar_wrapJNI.delete_GTAR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAR(String filename, OpenMode mode) {
    this(libgetar_wrapJNI.new_GTAR(filename, mode.swigValue()), true);
  }

  public void close() {
    libgetar_wrapJNI.GTAR_close(swigCPtr, this);
  }

  public byte[] readBytes(String path) {
    return libgetar_wrapJNI.GTAR_readBytes(swigCPtr, this, path);
}

  public VectorRecords getRecordTypes() {
    return new VectorRecords(libgetar_wrapJNI.GTAR_getRecordTypes(swigCPtr, this), true);
  }

  public VectorStrings queryFrames(Record target) {
    return new VectorStrings(libgetar_wrapJNI.GTAR_queryFrames(swigCPtr, this, Record.getCPtr(target), target), true);
  }

}
