/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libgetar_wrap;

public class libgetar_wrapJNI {
  public final static native long new_SharedArrayChar__SWIG_0();
  public final static native long new_SharedArrayChar__SWIG_1(long jarg1, long jarg2);
  public final static native long new_SharedArrayChar__SWIG_2(long jarg1, SharedArrayChar jarg1_);
  public final static native void delete_SharedArrayChar(long jarg1);
  public final static native void SharedArrayChar_copy(long jarg1, SharedArrayChar jarg1_, long jarg2, SharedArrayChar jarg2_);
  public final static native boolean SharedArrayChar_isNull(long jarg1, SharedArrayChar jarg1_);
  public final static native long SharedArrayChar_begin(long jarg1, SharedArrayChar jarg1_);
  public final static native long SharedArrayChar_end(long jarg1, SharedArrayChar jarg1_);
  public final static native long SharedArrayChar_get(long jarg1, SharedArrayChar jarg1_);
  public final static native long SharedArrayChar_size(long jarg1, SharedArrayChar jarg1_);
  public final static native void SharedArrayChar_release(long jarg1, SharedArrayChar jarg1_);
  public final static native void SharedArrayChar_swap(long jarg1, SharedArrayChar jarg1_, long jarg2, SharedArrayChar jarg2_);
  public final static native long new_VectorRecords__SWIG_0();
  public final static native long new_VectorRecords__SWIG_1(long jarg1);
  public final static native long VectorRecords_size(long jarg1, VectorRecords jarg1_);
  public final static native long VectorRecords_capacity(long jarg1, VectorRecords jarg1_);
  public final static native void VectorRecords_reserve(long jarg1, VectorRecords jarg1_, long jarg2);
  public final static native boolean VectorRecords_isEmpty(long jarg1, VectorRecords jarg1_);
  public final static native void VectorRecords_clear(long jarg1, VectorRecords jarg1_);
  public final static native void VectorRecords_add(long jarg1, VectorRecords jarg1_, long jarg2, Record jarg2_);
  public final static native long VectorRecords_get(long jarg1, VectorRecords jarg1_, int jarg2);
  public final static native void VectorRecords_set(long jarg1, VectorRecords jarg1_, int jarg2, long jarg3, Record jarg3_);
  public final static native void delete_VectorRecords(long jarg1);
  public final static native long new_VectorStrings__SWIG_0();
  public final static native long new_VectorStrings__SWIG_1(long jarg1);
  public final static native long VectorStrings_size(long jarg1, VectorStrings jarg1_);
  public final static native long VectorStrings_capacity(long jarg1, VectorStrings jarg1_);
  public final static native void VectorStrings_reserve(long jarg1, VectorStrings jarg1_, long jarg2);
  public final static native boolean VectorStrings_isEmpty(long jarg1, VectorStrings jarg1_);
  public final static native void VectorStrings_clear(long jarg1, VectorStrings jarg1_);
  public final static native void VectorStrings_add(long jarg1, VectorStrings jarg1_, String jarg2);
  public final static native String VectorStrings_get(long jarg1, VectorStrings jarg1_, int jarg2);
  public final static native void VectorStrings_set(long jarg1, VectorStrings jarg1_, int jarg2, String jarg3);
  public final static native void delete_VectorStrings(long jarg1);
  public final static native long new_GTAR(String jarg1, int jarg2);
  public final static native void GTAR_close(long jarg1, GTAR jarg1_);
  public final static native byte[] GTAR_readBytes(long jarg1, GTAR jarg1_, String jarg2);
  public final static native long GTAR_getRecordTypes(long jarg1, GTAR jarg1_);
  public final static native long GTAR_queryFrames(long jarg1, GTAR jarg1_, long jarg2, Record jarg2_);
  public final static native void delete_GTAR(long jarg1);
  public final static native long new_Record__SWIG_0();
  public final static native long new_Record__SWIG_1(String jarg1);
  public final static native long new_Record__SWIG_2(String jarg1, String jarg2, String jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long new_Record__SWIG_3(long jarg1, Record jarg1_);
  public final static native void Record_copy(long jarg1, Record jarg1_, long jarg2, Record jarg2_);
  public final static native String Record_nullifyIndex(long jarg1, Record jarg1_);
  public final static native long Record_withNullifiedIndex(long jarg1, Record jarg1_);
  public final static native String Record_getPath(long jarg1, Record jarg1_);
  public final static native String Record_getGroup(long jarg1, Record jarg1_);
  public final static native String Record_getName(long jarg1, Record jarg1_);
  public final static native String Record_getIndex(long jarg1, Record jarg1_);
  public final static native int Record_getBehavior(long jarg1, Record jarg1_);
  public final static native int Record_getFormat(long jarg1, Record jarg1_);
  public final static native int Record_getResolution(long jarg1, Record jarg1_);
  public final static native void Record_setIndex(long jarg1, Record jarg1_, String jarg2);
  public final static native void delete_Record(long jarg1);
}
