/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libgetar_wrap;

public class VectorStrings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorStrings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStrings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libgetar_wrapJNI.delete_VectorStrings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorStrings() {
    this(libgetar_wrapJNI.new_VectorStrings__SWIG_0(), true);
  }

  public VectorStrings(long n) {
    this(libgetar_wrapJNI.new_VectorStrings__SWIG_1(n), true);
  }

  public long size() {
    return libgetar_wrapJNI.VectorStrings_size(swigCPtr, this);
  }

  public long capacity() {
    return libgetar_wrapJNI.VectorStrings_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libgetar_wrapJNI.VectorStrings_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libgetar_wrapJNI.VectorStrings_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libgetar_wrapJNI.VectorStrings_clear(swigCPtr, this);
  }

  public void add(String x) {
    libgetar_wrapJNI.VectorStrings_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return libgetar_wrapJNI.VectorStrings_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    libgetar_wrapJNI.VectorStrings_set(swigCPtr, this, i, val);
  }

}
